-- AUTH-04: refresh tokens for silent re-authentication. Only the SHA-256 hex digest of the
-- token is stored, so a database dump yields nothing a client could present — token_hash is
-- CHAR(64) because a hex-formatted SHA-256 is exactly 64 characters, never fewer or more.
-- No separate index on token_hash: the UNIQUE constraint already provides one, matching how
-- users.email is handled in V1.
--
-- used_at / revoked_at are nullable and unwritten by the issuing/rotating code that lands with
-- this migration; they are the columns single-use rotation reuse-detection (D-03) and logout
-- (D-04) write. They live here rather than in a later ALTER because migrations are append-only
-- in this repo and both columns are already known to be needed.

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash CHAR(64)    NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
