-- AUTH-04: refresh tokens for silent re-authentication. Only the SHA-256 hex digest of the
-- token is stored, so a database dump yields nothing a client could present — a hex-formatted
-- SHA-256 is always exactly 64 characters. VARCHAR(64), not CHAR(64): Hibernate's schema
-- validator (ddl-auto=validate) checks the JDBC type code derived from the entity's `String`
-- field, which is always VARCHAR regardless of any columnDefinition override — CHAR(64) here
-- fails validation at boot no matter how the entity side is annotated. Postgres treats the two
-- identically in practice for a value that is always exactly 64 characters (no padding ever
-- applies), so VARCHAR is a free choice, not a compromise.
-- No separate index on token_hash: the UNIQUE constraint already provides one, matching how
-- users.email is handled in V1.
--
-- used_at / revoked_at are nullable and unwritten by the issuing/rotating code that lands with
-- this migration; they are the columns single-use rotation reuse-detection (D-03) and logout
-- (D-04) write. They live here rather than in a later ALTER because migrations are append-only
-- in this repo and both columns are already known to be needed.

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
