CREATE TABLE trips (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title          VARCHAR(150) NOT NULL,
    description    TEXT,
    tags           TEXT[],
    visibility     VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    status         VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    route_geometry JSONB,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_trips_user_id ON trips(user_id);