CREATE TABLE places (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(200) NOT NULL,
    latitude          DOUBLE PRECISION NOT NULL,
    longitude         DOUBLE PRECISION NOT NULL,
    address           VARCHAR(300),
    external_place_id VARCHAR(150),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- primary dedup key (external/Mapbox id): unique only when present
CREATE UNIQUE INDEX idx_places_external_id
    ON places(external_place_id)
    WHERE external_place_id IS NOT NULL;

-- fallback dedup lookup (name + coordinates)
CREATE INDEX idx_places_name_lat_lng ON places(name, latitude, longitude);