CREATE TABLE stops (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id      BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    name         VARCHAR(150) NOT NULL,
    address      VARCHAR(255),
    latitude     DOUBLE PRECISION NOT NULL,
    longitude    DOUBLE PRECISION NOT NULL,
    stop_order   INT NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    notes        TEXT,
    created_at   TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_stops_trip_id ON stops(trip_id);