CREATE TABLE stops (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id    BIGINT NOT NULL REFERENCES trips(id)  ON DELETE CASCADE,
    place_id   BIGINT NOT NULL REFERENCES places(id),
    stop_order INT NOT NULL,
    status     VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    notes      TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_stops_trip_id  ON stops(trip_id);
CREATE INDEX idx_stops_place_id ON stops(place_id);