CREATE TABLE stop_photos (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stop_id               BIGINT NOT NULL REFERENCES stops(id) ON DELETE CASCADE,
    url                   TEXT NOT NULL,
    cloudinary_public_id  TEXT,
    caption               TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_stop_photos_stop_id ON stop_photos(stop_id);